name: Deploy static website

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Test workflow
        run: echo "GitHub Actions workflow started"
